/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jdk/jni.h"
/* Header for class com_keyilx_jni_JNIDemo */

#ifndef _Included_com_keyilx_jni_JNIDemo
#define _Included_com_keyilx_jni_JNIDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_keyilx_jni_JNIDemo
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_keyilx_jni_JNIDemo_getStringFromC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
